# Generated by Django 5.1.5 on 2025-02-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("seller", "Seller"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                ],
                default="regular",
                max_length=10,
            ),
        ),
    ]
